2016-06-29 14:40:19,812 [Thread-2:111128] [django.request:256] [ERROR]- Internal Server Error: /admin/bbs/bbs/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "H:\Coding\workstation\BBS_Pro\src\BBS_Pro\urls.py", line 54, in <module>
    url(r'^ckeditor/', include('ckeditor.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls
2016-06-29 14:40:28,907 [Thread-3:111152] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "H:\Coding\workstation\BBS_Pro\src\BBS_Pro\urls.py", line 54, in <module>
    url(r'^ckeditor/', include('ckeditor.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls
2016-06-29 14:42:02,283 [Thread-4:111456] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "H:\Coding\workstation\BBS_Pro\src\BBS_Pro\urls.py", line 54, in <module>
    url(r'^ckeditor/', include('ckeditor.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls
2016-06-29 14:42:05,545 [Thread-5:111484] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "H:\Coding\workstation\BBS_Pro\src\BBS_Pro\urls.py", line 54, in <module>
    url(r'^ckeditor/', include('ckeditor.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls
2016-06-29 14:42:07,480 [Thread-6:111488] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "H:\Coding\workstation\BBS_Pro\src\BBS_Pro\urls.py", line 54, in <module>
    url(r'^ckeditor/', include('ckeditor.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls
2016-06-29 14:42:08,398 [Thread-7:111496] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "H:\Coding\workstation\BBS_Pro\src\BBS_Pro\urls.py", line 54, in <module>
    url(r'^ckeditor/', include('ckeditor.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls
2016-06-29 14:42:09,289 [Thread-8:111500] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "H:\Coding\workstation\BBS_Pro\src\BBS_Pro\urls.py", line 54, in <module>
    url(r'^ckeditor/', include('ckeditor.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls
2016-06-29 14:42:09,387 [Thread-9:111504] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "H:\Coding\workstation\BBS_Pro\src\BBS_Pro\urls.py", line 54, in <module>
    url(r'^ckeditor/', include('ckeditor.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls
2016-06-29 14:42:09,548 [Thread-10:111508] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "H:\Coding\workstation\BBS_Pro\src\BBS_Pro\urls.py", line 54, in <module>
    url(r'^ckeditor/', include('ckeditor.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls
2016-06-29 14:42:10,410 [Thread-11:111512] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "H:\Coding\workstation\BBS_Pro\src\BBS_Pro\urls.py", line 54, in <module>
    url(r'^ckeditor/', include('ckeditor.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls
2016-06-29 14:42:11,029 [Thread-12:111516] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "H:\Coding\workstation\BBS_Pro\src\BBS_Pro\urls.py", line 54, in <module>
    url(r'^ckeditor/', include('ckeditor.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls
2016-06-29 14:42:11,230 [Thread-13:111520] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "H:\Coding\workstation\BBS_Pro\src\BBS_Pro\urls.py", line 54, in <module>
    url(r'^ckeditor/', include('ckeditor.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls
2016-06-29 14:42:11,461 [Thread-14:111524] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "H:\Coding\workstation\BBS_Pro\src\BBS_Pro\urls.py", line 54, in <module>
    url(r'^ckeditor/', include('ckeditor.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls
2016-06-29 14:42:11,657 [Thread-15:111528] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "H:\Coding\workstation\BBS_Pro\src\BBS_Pro\urls.py", line 54, in <module>
    url(r'^ckeditor/', include('ckeditor.urls')),
  File "D:\Python27\lib\site-packages\django\conf\urls\__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named urls
2016-06-29 14:44:07,694 [Thread-22:111040] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 14:44:10,119 [Thread-42:111132] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 14:50:00,657 [Thread-25:111364] [django.request:170] [WARNING]- Not Found: /statics/admin/js/jquery.min.js
2016-06-29 14:50:00,928 [Thread-28:107972] [django.request:170] [WARNING]- Not Found: /statics/admin/js/jquery.min.js
2016-06-29 14:50:07,676 [Thread-45:110976] [django.request:170] [WARNING]- Not Found: /statics/admin/js/jquery.min.js
2016-06-29 14:50:07,897 [Thread-48:110676] [django.request:170] [WARNING]- Not Found: /statics/admin/js/jquery.min.js
2016-06-29 14:50:30,928 [Thread-61:107976] [django.request:170] [WARNING]- Not Found: /statics/admin/js/jquery.min.js
2016-06-29 14:52:57,632 [Thread-78:110080] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 14:52:58,181 [Thread-80:109844] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 14:53:30,681 [Thread-93:111212] [django.request:170] [WARNING]- Not Found: /statics/admin/js/jquery.min.js
2016-06-29 14:53:31,046 [Thread-96:111008] [django.request:170] [WARNING]- Not Found: /statics/admin/js/jquery.min.js
2016-06-29 15:06:29,908 [Thread-120:111000] [django.request:170] [WARNING]- Not Found: /statics/admin/js/jquery.min.js
2016-06-29 15:06:30,115 [Thread-123:112168] [django.request:170] [WARNING]- Not Found: /statics/admin/js/jquery.min.js
2016-06-29 15:06:46,895 [Thread-12:111680] [django.request:170] [WARNING]- Not Found: /statics/admin/js/jquery.min.js
2016-06-29 15:06:47,131 [Thread-21:112384] [django.request:170] [WARNING]- Not Found: /statics/admin/js/jquery.min.js
2016-06-29 15:16:57,710 [Thread-3:112416] [django.request:256] [ERROR]- Internal Server Error: /bbs/bbsdetail/1/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "H:\Coding\workstation\BBS_Pro\src\bbs\views.py", line 106, in bbs_detail
    'user': request.user,}
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\Python27\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\Python27\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "D:\Python27\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\Python27\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'static', expected 'endblock'
2016-06-29 15:20:07,276 [Thread-264:113228] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 15:20:07,365 [Thread-265:113232] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 15:21:24,263 [Thread-285:112208] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 15:21:24,734 [Thread-286:113548] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 15:30:34,154 [Thread-354:110664] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 15:30:41,026 [Thread-355:109480] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 15:55:24,108 [Thread-2:114332] [django.request:256] [ERROR]- Internal Server Error: /assets/add
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 108, in get_response
    response = middleware_method(request)
  File "D:\Python27\lib\site-packages\django\middleware\common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 368, in resolve
    sub_match = pattern.resolve(new_path)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 368, in resolve
    sub_match = pattern.resolve(new_path)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 240, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 247, in callback
    self._callback = get_callable(self._callback_str)
  File "D:\Python27\lib\site-packages\django\utils\lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 106, in get_callable
    mod = import_module(mod_name)
  File "D:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "H:\Coding\workstation\BBS_Pro\src\assets\views.py", line 7, in <module>
    from forms import HostForm
  File "H:\Coding\workstation\BBS_Pro\src\assets\forms.py", line 19, in <module>
    class HostForm(ModelForm):
  File "H:\Coding\workstation\BBS_Pro\src\assets\forms.py", line 37, in HostForm
    kv_user = map(lambda mr:(mr[1], mr[1]), user_list)
  File "H:\Coding\workstation\BBS_Pro\src\assets\forms.py", line 37, in <lambda>
    kv_user = map(lambda mr:(mr[1], mr[1]), user_list)
IndexError: tuple index out of range
2016-06-29 16:03:13,085 [Thread-20:115016] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 16:08:05,025 [Thread-144:114660] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 16:08:05,186 [Thread-145:114028] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 16:11:04,539 [Thread-253:115556] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 16:11:04,928 [Thread-255:115192] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 16:55:22,362 [Thread-52:117636] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 16:55:22,509 [Thread-53:115248] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-29 16:56:12,621 [Thread-154:117424] [django.request:170] [WARNING]- Not Found: /assets/add/
2016-06-29 16:58:48,374 [Thread-167:117600] [django.request:256] [ERROR]- Internal Server Error: /assets/add
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 108, in get_response
    response = middleware_method(request)
  File "D:\Python27\lib\site-packages\django\middleware\common.py", line 84, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/assets/add/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2016-06-29 17:02:44,509 [Thread-219:117384] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-06-29 17:03:22,391 [Thread-230:117860] [django.request:256] [ERROR]- Internal Server Error: /assets/add
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 108, in get_response
    response = middleware_method(request)
  File "D:\Python27\lib\site-packages\django\middleware\common.py", line 84, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/assets/add/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2016-06-29 17:03:47,051 [Thread-272:118140] [django.request:256] [ERROR]- Internal Server Error: /assets/add/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "H:\Coding\workstation\BBS_Pro\src\assets\views.py", line 23, in add
    if form.is_valid():
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 184, in is_valid
    return self.is_bound and not self.errors
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 176, in errors
    self.full_clean()
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 394, in full_clean
    self._post_clean()
  File "D:\Python27\lib\site-packages\django\forms\models.py", line 427, in _post_clean
    self.instance = construct_instance(self, self.instance, opts.fields, construct_instance_exclude)
  File "D:\Python27\lib\site-packages\django\forms\models.py", line 62, in construct_instance
    f.save_form_data(instance, cleaned_data[f.name])
  File "D:\Python27\lib\site-packages\django\db\models\fields\__init__.py", line 874, in save_form_data
    setattr(instance, self.name, data)
  File "D:\Python27\lib\site-packages\django\db\models\fields\related.py", line 627, in __set__
    self.field.rel.to._meta.object_name,
ValueError: Cannot assign "u'suqirui'": "Host.supporter" must be a "BBS_user" instance.
2016-06-29 17:03:47,575 [Thread-273:118148] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-06-29 17:07:35,000 [Thread-285:118736] [django.request:170] [WARNING]- Not Found: /statics/admin/js/jquery.min.js
2016-06-29 17:09:53,808 [Thread-309:117388] [django.request:256] [ERROR]- Internal Server Error: /assets/add/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "H:\Coding\workstation\BBS_Pro\src\assets\views.py", line 23, in add
    if form.is_valid():
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 184, in is_valid
    return self.is_bound and not self.errors
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 176, in errors
    self.full_clean()
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 394, in full_clean
    self._post_clean()
  File "D:\Python27\lib\site-packages\django\forms\models.py", line 427, in _post_clean
    self.instance = construct_instance(self, self.instance, opts.fields, construct_instance_exclude)
  File "D:\Python27\lib\site-packages\django\forms\models.py", line 62, in construct_instance
    f.save_form_data(instance, cleaned_data[f.name])
  File "D:\Python27\lib\site-packages\django\db\models\fields\__init__.py", line 874, in save_form_data
    setattr(instance, self.name, data)
  File "D:\Python27\lib\site-packages\django\db\models\fields\related.py", line 627, in __set__
    self.field.rel.to._meta.object_name,
ValueError: Cannot assign "u'devops'": "Host.supporter" must be a "BBS_user" instance.
2016-06-29 17:19:03,691 [Thread-43:117376] [django.request:256] [ERROR]- Internal Server Error: /assets/add/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "H:\Coding\workstation\BBS_Pro\src\assets\views.py", line 23, in add
    if form.is_valid():
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 184, in is_valid
    return self.is_bound and not self.errors
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 176, in errors
    self.full_clean()
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 392, in full_clean
    self._clean_fields()
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 410, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()
  File "H:\Coding\workstation\BBS_Pro\src\assets\forms.py", line 54, in clean_supporter
    return BBS_user.objects.get(user = User.objects.get(username=self.clean_data('supporter')))
AttributeError: 'HostForm' object has no attribute 'clean_data'
2016-06-29 17:19:04,196 [Thread-44:117812] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-06-29 17:19:29,460 [Thread-2:118692] [django.request:256] [ERROR]- Internal Server Error: /assets/add/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "H:\Coding\workstation\BBS_Pro\src\assets\views.py", line 23, in add
    if form.is_valid():
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 184, in is_valid
    return self.is_bound and not self.errors
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 176, in errors
    self.full_clean()
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 392, in full_clean
    self._clean_fields()
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 410, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()
  File "H:\Coding\workstation\BBS_Pro\src\assets\forms.py", line 54, in clean_supporter
    return BBS_user.objects.get(user = User.objects.get(username=self.cleaned_data('supporter')))
TypeError: 'dict' object is not callable
2016-06-29 17:21:33,253 [Thread-43:118236] [django.request:256] [ERROR]- Internal Server Error: /assets/add/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "H:\Coding\workstation\BBS_Pro\src\assets\views.py", line 23, in add
    if form.is_valid():
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 184, in is_valid
    return self.is_bound and not self.errors
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 176, in errors
    self.full_clean()
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 392, in full_clean
    self._clean_fields()
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 410, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()
  File "H:\Coding\workstation\BBS_Pro\src\assets\forms.py", line 54, in clean_supporter
    user = User.objects.get(username=self.cleaned_data('supporter'))
TypeError: 'dict' object is not callable
2016-06-29 17:21:33,779 [Thread-44:117844] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-06-29 17:22:27,790 [Thread-43:118652] [django.request:256] [ERROR]- Internal Server Error: /assets/add/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "H:\Coding\workstation\BBS_Pro\src\assets\views.py", line 23, in add
    if form.is_valid():
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 184, in is_valid
    return self.is_bound and not self.errors
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 176, in errors
    self.full_clean()
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 394, in full_clean
    self._post_clean()
  File "D:\Python27\lib\site-packages\django\forms\models.py", line 427, in _post_clean
    self.instance = construct_instance(self, self.instance, opts.fields, construct_instance_exclude)
  File "D:\Python27\lib\site-packages\django\forms\models.py", line 62, in construct_instance
    f.save_form_data(instance, cleaned_data[f.name])
  File "D:\Python27\lib\site-packages\django\db\models\fields\__init__.py", line 874, in save_form_data
    setattr(instance, self.name, data)
  File "D:\Python27\lib\site-packages\django\db\models\fields\related.py", line 627, in __set__
    self.field.rel.to._meta.object_name,
ValueError: Cannot assign "u'\u5317\u4eac\u4e16\u7eaa\u4e92\u8054\u673a\u623f'": "Host.mroom" must be a "Machine_Room" instance.
2016-06-29 17:22:29,259 [Thread-44:118376] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-06-29 17:35:23,869 [Thread-45:118800] [django.request:256] [ERROR]- Internal Server Error: /assets/add
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 108, in get_response
    response = middleware_method(request)
  File "D:\Python27\lib\site-packages\django\middleware\common.py", line 84, in process_request
    "settings.") % (new_url[0], new_url[1]))
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/assets/add/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2016-06-29 17:35:46,586 [Thread-143:118652] [django.request:256] [ERROR]- Internal Server Error: /assets/add/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "H:\Coding\workstation\BBS_Pro\src\assets\views.py", line 23, in add
    if form.is_valid():
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 184, in is_valid
    return self.is_bound and not self.errors
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 176, in errors
    self.full_clean()
  File "D:\Python27\lib\site-packages\django\forms\forms.py", line 394, in full_clean
    self._post_clean()
  File "D:\Python27\lib\site-packages\django\forms\models.py", line 427, in _post_clean
    self.instance = construct_instance(self, self.instance, opts.fields, construct_instance_exclude)
  File "D:\Python27\lib\site-packages\django\forms\models.py", line 62, in construct_instance
    f.save_form_data(instance, cleaned_data[f.name])
  File "D:\Python27\lib\site-packages\django\db\models\fields\__init__.py", line 874, in save_form_data
    setattr(instance, self.name, data)
  File "D:\Python27\lib\site-packages\django\db\models\fields\related.py", line 627, in __set__
    self.field.rel.to._meta.object_name,
ValueError: Cannot assign "u'\u5317\u4eac\u4e16\u7eaa\u4e92\u8054\u673a\u623f'": "Host.mroom" must be a "Machine_Room" instance.
2016-06-30 13:08:10,220 [Thread-44:127652] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-30 13:08:23,286 [Thread-53:127720] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-30 13:08:35,556 [Thread-57:127784] [django.request:170] [WARNING]- Not Found: /statics/admin/js/jquery.min.js
2016-06-30 13:08:35,992 [Thread-61:127808] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-06-30 13:28:55,548 [Thread-77:128856] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-30 13:28:56,144 [Thread-79:126792] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-30 13:34:38,279 [Thread-105:127664] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-30 14:13:41,661 [Thread-45:56612] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-30 14:14:02,279 [Thread-53:124564] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-06-30 14:47:12,842 [Thread-2:131340] [django.request:256] [ERROR]- Internal Server Error: /bbs/bbsdetail/45/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "H:\Coding\workstation\BBS_Pro\src\bbs\views.py", line 106, in bbs_detail
    'user': request.user,}
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 433, in _reverse_with_prefix
    self._populate()
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 308, in _populate
    for name in pattern.reverse_dict:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in reverse_dict
    self._populate()
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 326, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 247, in callback
    self._callback = get_callable(self._callback_str)
  File "D:\Python27\lib\site-packages\django\utils\lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 127, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import 'assets.views.search'. View does not exist in module assets.views.
2016-06-30 14:47:13,983 [Thread-3:131344] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-06-30 14:49:08,483 [Thread-9:131808] [django.request:256] [ERROR]- Internal Server Error: /bbs/bbsdetail/45/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "H:\Coding\workstation\BBS_Pro\src\bbs\views.py", line 106, in bbs_detail
    'user': request.user,}
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\Python27\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\Python27\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\Python27\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\Python27\lib\site-packages\django\template\defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 433, in _reverse_with_prefix
    self._populate()
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 308, in _populate
    for name in pattern.reverse_dict:
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 338, in reverse_dict
    self._populate()
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 326, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 247, in callback
    self._callback = get_callable(self._callback_str)
  File "D:\Python27\lib\site-packages\django\utils\lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "D:\Python27\lib\site-packages\django\core\urlresolvers.py", line 127, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import 'assets.views.search'. View does not exist in module assets.views.
2016-06-30 14:49:09,561 [Thread-10:131812] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-06-30 14:49:59,767 [Thread-44:131172] [django.request:256] [ERROR]- Internal Server Error: /assets/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "H:\Coding\workstation\BBS_Pro\src\assets\views.py", line 47, in search
    host_msg_lists = Host.objects.filter(Q(ipaddr__icontains = search_q) | Q(hostname__icontains = search_q))
  File "D:\Python27\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1301, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1323, in _add_q
    current_negated, allow_joins)
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1328, in _add_q
    current_negated=current_negated, connector=connector, allow_joins=allow_joins)
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1150, in build_filter
    value, lookups, used_joins = self.prepare_lookup_value(value, lookups, can_reuse, allow_joins)
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 990, in prepare_lookup_value
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
2016-06-30 14:50:01,007 [Thread-45:99336] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-06-30 14:51:58,026 [Thread-2:131424] [django.request:256] [ERROR]- Internal Server Error: /assets/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "H:\Coding\workstation\BBS_Pro\src\assets\views.py", line 47, in search
    host_msg_lists = Host.objects.filter(Q(ipaddr__icontains = search_q) | Q(hostname__icontains = search_q))
  File "D:\Python27\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Python27\lib\site-packages\django\db\models\query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1301, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1323, in _add_q
    current_negated, allow_joins)
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1328, in _add_q
    current_negated=current_negated, connector=connector, allow_joins=allow_joins)
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1150, in build_filter
    value, lookups, used_joins = self.prepare_lookup_value(value, lookups, can_reuse, allow_joins)
  File "D:\Python27\lib\site-packages\django\db\models\sql\query.py", line 990, in prepare_lookup_value
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
2016-06-30 14:51:58,882 [Thread-3:131432] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-06-30 14:52:08,244 [Thread-46:131692] [django.request:256] [ERROR]- Internal Server Error: /assets/search/
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "H:\Coding\workstation\BBS_Pro\src\assets\views.py", line 50, in search
    'host_lists': host_msg_lists,
  File "D:\Python27\lib\site-packages\django\shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python27\lib\site-packages\django\template\loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: search_assets_lists.html
2016-06-30 14:52:09,032 [Thread-47:131700] [django.request:170] [WARNING]- Not Found: /favicon.ico
2016-06-30 15:04:48,582 [Thread-59:131496] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-30 15:12:10,000 [Thread-107:132476] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2016-06-30 16:22:19,892 [Thread-120:135600] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 03:58:31,247 [Thread-2:15584] [django.request:170] [WARNING]- Not Found: /api/spec
2017-11-19 03:58:31,460 [Thread-3:16100] [django.request:170] [WARNING]- Not Found: /api/spec
2017-11-19 03:58:31,578 [Thread-4:16660] [django.request:170] [WARNING]- Not Found: /favicon.ico
2017-11-19 03:58:36,042 [Thread-23:17120] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 03:58:36,361 [Thread-29:17168] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 03:58:57,887 [Thread-57:10736] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 03:59:10,276 [Thread-64:13332] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 03:59:21,178 [Thread-105:4680] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 04:24:45,443 [Thread-158:8492] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 04:24:49,108 [Thread-161:14204] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 04:25:52,882 [Thread-283:6688] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 04:25:53,025 [Thread-284:13416] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 04:25:59,460 [Thread-290:16888] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 04:26:11,779 [Thread-298:17184] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 04:41:58,161 [Thread-301:17304] [django.request:170] [WARNING]- Not Found: /announce.php
2017-11-19 04:41:58,168 [Thread-302:16360] [django.request:170] [WARNING]- Not Found: /announce.php
2017-11-19 04:49:23,029 [Thread-303:4936] [django.request:170] [WARNING]- Not Found: /announce.php
2017-11-19 04:49:23,605 [Thread-304:17052] [django.request:170] [WARNING]- Not Found: /announce.php
2017-11-19 04:58:38,619 [Thread-305:16764] [django.request:170] [WARNING]- Not Found: /announce.php
2017-11-19 04:58:39,119 [Thread-306:3736] [django.request:170] [WARNING]- Not Found: /announce.php
2017-11-19 05:03:26,996 [Thread-307:17380] [django.request:170] [WARNING]- Not Found: /announce.php
2017-11-19 05:03:30,950 [Thread-308:2400] [django.request:170] [WARNING]- Not Found: /announce.php
2017-11-19 05:05:45,628 [Thread-309:17068] [django.request:170] [WARNING]- Not Found: /announce.php
2017-11-19 05:05:46,380 [Thread-310:13880] [django.request:170] [WARNING]- Not Found: /announce.php
2017-11-19 06:39:20,436 [Thread-329:10352] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 06:39:20,763 [Thread-335:8104] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 07:20:34,711 [Thread-372:9288] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 07:20:34,989 [Thread-375:3080] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 08:53:12,444 [Thread-459:15036] [django.request:170] [WARNING]- Not Found: /favicon.ico
2017-11-19 08:53:54,736 [Thread-473:4332] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 08:54:33,719 [Thread-489:15740] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 08:54:33,888 [Thread-490:1636] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 08:57:07,832 [Thread-517:15512] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 08:57:07,851 [Thread-518:14576] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 10:23:32,963 [Thread-27:6832] [django.request:170] [WARNING]- Not Found: /favicon.ico
2017-11-19 10:25:41,444 [Thread-11:16504] [django.request:170] [WARNING]- Not Found: /favicon.ico
2017-11-19 10:25:42,921 [Thread-21:14376] [django.request:170] [WARNING]- Not Found: /favicon.ico
2017-11-19 10:36:28,171 [Thread-4:14024] [django.request:256] [ERROR]- Internal Server Error: /admin/myauth/user/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\options.py", line 1548, in changelist_view
    self.list_max_show_all, self.list_editable, self)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\views\main.py", line 82, in __init__
    self.get_results(request)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\views\main.py", line 177, in get_results
    result_count = paginator.count
  File "D:\virtualenv\py27django\lib\site-packages\django\core\paginator.py", line 72, in _get_count
    self._count = self.object_list.count()
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 318, in count
    return self.query.get_count(using=self.db)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\sql\query.py", line 464, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\sql\query.py", line 445, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\sql\compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\sqlite3\base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: myauth_user
2017-11-19 10:36:29,056 [Thread-6:17624] [django.request:256] [ERROR]- Internal Server Error: /admin/myauth/user/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\options.py", line 1548, in changelist_view
    self.list_max_show_all, self.list_editable, self)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\views\main.py", line 82, in __init__
    self.get_results(request)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\views\main.py", line 177, in get_results
    result_count = paginator.count
  File "D:\virtualenv\py27django\lib\site-packages\django\core\paginator.py", line 72, in _get_count
    self._count = self.object_list.count()
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 318, in count
    return self.query.get_count(using=self.db)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\sql\query.py", line 464, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\sql\query.py", line 445, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\sql\compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\sqlite3\base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: myauth_user
2017-11-19 10:36:52,966 [Thread-8:7028] [django.request:256] [ERROR]- Internal Server Error: /admin/myauth/user/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\options.py", line 1548, in changelist_view
    self.list_max_show_all, self.list_editable, self)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\views\main.py", line 82, in __init__
    self.get_results(request)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\views\main.py", line 177, in get_results
    result_count = paginator.count
  File "D:\virtualenv\py27django\lib\site-packages\django\core\paginator.py", line 72, in _get_count
    self._count = self.object_list.count()
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 318, in count
    return self.query.get_count(using=self.db)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\sql\query.py", line 464, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\sql\query.py", line 445, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\sql\compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\sqlite3\base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: myauth_user
2017-11-19 10:36:53,545 [Thread-10:7164] [django.request:256] [ERROR]- Internal Server Error: /admin/myauth/user/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\utils\decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\options.py", line 1548, in changelist_view
    self.list_max_show_all, self.list_editable, self)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\views\main.py", line 82, in __init__
    self.get_results(request)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\admin\views\main.py", line 177, in get_results
    result_count = paginator.count
  File "D:\virtualenv\py27django\lib\site-packages\django\core\paginator.py", line 72, in _get_count
    self._count = self.object_list.count()
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 318, in count
    return self.query.get_count(using=self.db)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\sql\query.py", line 464, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\sql\query.py", line 445, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\sql\compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\sqlite3\base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: myauth_user
2017-11-19 10:48:14,150 [Thread-15:15200] [django.request:170] [WARNING]- Not Found: /media/media/avatar/github.jpg
2017-11-19 10:48:14,525 [Thread-16:12244] [django.request:170] [WARNING]- Not Found: /media/media/avatar/github.jpg
2017-11-19 10:48:19,917 [Thread-17:15132] [django.request:170] [WARNING]- Not Found: /media/avatar/github.jpg
2017-11-19 10:48:20,227 [Thread-18:9992] [django.request:170] [WARNING]- Not Found: /media/avatar/github.jpg
2017-11-19 10:49:24,950 [Thread-8:1744] [django.request:170] [WARNING]- Not Found: /media/media/avatar/github.jpg
2017-11-19 10:49:25,322 [Thread-9:14956] [django.request:170] [WARNING]- Not Found: /media/media/avatar/github.jpg
2017-11-19 10:49:28,796 [Thread-10:8356] [django.request:170] [WARNING]- Not Found: /media/avatar/github.jpg
2017-11-19 10:49:29,101 [Thread-11:14896] [django.request:170] [WARNING]- Not Found: /media/avatar/github.jpg
2017-11-19 10:49:31,668 [Thread-12:17532] [django.request:170] [WARNING]- Not Found: /avatar/github.jpg
2017-11-19 10:49:31,970 [Thread-13:13104] [django.request:170] [WARNING]- Not Found: /avatar/github.jpg
2017-11-19 10:49:38,788 [Thread-14:5688] [django.request:170] [WARNING]- Not Found: /media/github.jpg
2017-11-19 10:49:39,089 [Thread-15:18112] [django.request:170] [WARNING]- Not Found: /media/github.jpg
2017-11-19 10:49:52,819 [Thread-34:15132] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 10:49:52,976 [Thread-38:15240] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 11:01:11,003 [Thread-2:15632] [django.request:170] [WARNING]- Not Found: /media/media/avatar/github.jpg
2017-11-19 11:01:11,243 [Thread-3:10624] [django.request:170] [WARNING]- Not Found: /media/media/avatar/github.jpg
2017-11-19 11:01:15,171 [Thread-4:15112] [django.request:170] [WARNING]- Not Found: /media/avatar/github.jpg
2017-11-19 11:01:15,477 [Thread-5:1564] [django.request:170] [WARNING]- Not Found: /media/avatar/github.jpg
2017-11-19 11:01:18,750 [Thread-6:15032] [django.request:170] [WARNING]- Not Found: /avatar/github.jpg
2017-11-19 11:01:18,818 [Thread-7:18144] [django.request:170] [WARNING]- Not Found: /avatar/github.jpg
2017-11-19 11:02:27,584 [Thread-37:15620] [django.request:170] [WARNING]- Not Found: /media/avatar/github_LIcDvcH.jpg
2017-11-19 11:02:28,118 [Thread-38:13960] [django.request:170] [WARNING]- Not Found: /media/avatar/github_LIcDvcH.jpg
2017-11-19 11:03:12,339 [Thread-42:10360] [django.request:170] [WARNING]- Not Found: /media/static/github_LIcDvcH.jpg
2017-11-19 11:03:12,404 [Thread-43:14236] [django.request:170] [WARNING]- Not Found: /media/static/github_LIcDvcH.jpg
2017-11-19 11:03:18,322 [Thread-46:15240] [django.request:170] [WARNING]- Not Found: /media/avatar/github_LIcDvcH.jpg
2017-11-19 11:03:18,384 [Thread-47:14052] [django.request:170] [WARNING]- Not Found: /media/avatar/github_LIcDvcH.jpg
2017-11-19 11:03:48,019 [Thread-54:10148] [django.request:170] [WARNING]- Not Found: /avatar/github_LIcDvcH.jpg
2017-11-19 11:03:48,253 [Thread-55:17724] [django.request:170] [WARNING]- Not Found: /avatar/github_LIcDvcH.jpg
2017-11-19 12:35:45,028 [Thread-62:17960] [django.request:170] [WARNING]- Not Found: /media/avatar/github_LIcDvcH.jpg
2017-11-19 12:35:45,095 [Thread-63:13760] [django.request:170] [WARNING]- Not Found: /media/avatar/github_LIcDvcH.jpg
2017-11-19 12:36:09,841 [Thread-65:436] [django.request:170] [WARNING]- Not Found: /media/avatar/github_LIcDvcH.jpg
2017-11-19 12:36:10,091 [Thread-66:16120] [django.request:170] [WARNING]- Not Found: /media/avatar/github_LIcDvcH.jpg
2017-11-19 13:28:12,765 [Thread-63:18756] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 13:45:40,940 [Thread-88:11912] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 13:45:41,148 [Thread-89:2080] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 13:45:45,059 [Thread-91:18972] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 13:45:47,036 [Thread-111:1744] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 13:45:47,625 [Thread-119:6860] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 13:45:53,446 [Thread-156:18608] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 13:45:54,058 [Thread-164:17072] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 13:48:18,687 [Thread-184:9916] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\eoms\bbs\views.py", line 164, in dashboard
    {'user': request.user}
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
2017-11-19 13:48:19,298 [Thread-185:11128] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\eoms\bbs\views.py", line 164, in dashboard
    {'user': request.user}
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
2017-11-19 13:49:04,198 [Thread-186:3600] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\eoms\bbs\views.py", line 164, in dashboard
    {'user': request.user}
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
2017-11-19 13:49:04,871 [Thread-187:17600] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\eoms\bbs\views.py", line 164, in dashboard
    {'user': request.user}
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
2017-11-19 13:49:13,065 [Thread-188:14724] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\eoms\bbs\views.py", line 164, in dashboard
    {'user': request.user}
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
2017-11-19 13:49:13,618 [Thread-189:12400] [django.request:256] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Project\eoms\bbs\views.py", line 164, in dashboard
    {'user': request.user}
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 99, in render_to_string
    return template.render(context, request)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 113, in render
    compiled_parent = self.get_parent(context)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 110, in get_parent
    return context.template.engine.get_template(parent)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'static'
2017-11-19 13:50:02,171 [Thread-207:17692] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 13:50:02,461 [Thread-210:17828] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 13:50:21,582 [Thread-285:11776] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 13:50:21,990 [Thread-286:19916] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 13:50:24,769 [Thread-291:18120] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 14:13:24,792 [Thread-299:19312] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 14:17:17,697 [Thread-3:14556] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 14:17:17,802 [Thread-4:18016] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 14:26:18,296 [Thread-20:3544] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 14:26:18,384 [Thread-21:19700] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 14:26:24,984 [Thread-23:17812] [django.request:170] [WARNING]- Not Found: /myauth
2017-11-19 14:26:25,052 [Thread-24:7572] [django.request:170] [WARNING]- Not Found: /myauth
2017-11-19 14:26:35,983 [Thread-31:18628] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 14:26:42,927 [Thread-37:19684] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 14:26:43,023 [Thread-38:19568] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-19 15:08:59,043 [Thread-270:16824] [django.request:256] [ERROR]- Internal Server Error: /auth/list/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\myauth\views.py", line 38, in userList
    return render(request, 'list.html', {"form": allUser})
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 868, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 912, in ifequal
    return do_ifequal(parser, token, False)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 883, in do_ifequal
    nodelist_true = parser.parse(('else', end_tag))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'endfor', expected 'else' \u6216 'endifequal'
2017-11-19 15:09:13,911 [Thread-276:6540] [django.request:256] [ERROR]- Internal Server Error: /auth/list/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\myauth\views.py", line 38, in userList
    return render(request, 'list.html', {"form": allUser})
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 868, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 912, in ifequal
    return do_ifequal(parser, token, False)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 883, in do_ifequal
    nodelist_true = parser.parse(('else', end_tag))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'endfor', expected 'else' \u6216 'endifequal'
2017-11-19 15:09:14,476 [Thread-277:19264] [django.request:256] [ERROR]- Internal Server Error: /auth/list/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\myauth\views.py", line 38, in userList
    return render(request, 'list.html', {"form": allUser})
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 868, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 912, in ifequal
    return do_ifequal(parser, token, False)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 883, in do_ifequal
    nodelist_true = parser.parse(('else', end_tag))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'endfor', expected 'else' \u6216 'endifequal'
2017-11-19 15:19:15,038 [Thread-309:10100] [django.request:256] [ERROR]- Internal Server Error: /auth/list/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\myauth\views.py", line 38, in userList
    return render(request, 'list.html', {"form": allUser})
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 868, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 912, in ifequal
    return do_ifequal(parser, token, False)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 883, in do_ifequal
    nodelist_true = parser.parse(('else', end_tag))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'endfor', expected 'else' \u6216 'endifequal'
2017-11-19 15:19:17,516 [Thread-310:7128] [django.request:256] [ERROR]- Internal Server Error: /auth/list/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\myauth\views.py", line 38, in userList
    return render(request, 'list.html', {"form": allUser})
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 868, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 912, in ifequal
    return do_ifequal(parser, token, False)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 883, in do_ifequal
    nodelist_true = parser.parse(('else', end_tag))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'endfor', expected 'else' \u6216 'endifequal'
2017-11-19 15:19:18,036 [Thread-311:20308] [django.request:256] [ERROR]- Internal Server Error: /auth/list/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\myauth\views.py", line 38, in userList
    return render(request, 'list.html', {"form": allUser})
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 868, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 912, in ifequal
    return do_ifequal(parser, token, False)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 883, in do_ifequal
    nodelist_true = parser.parse(('else', end_tag))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'endfor', expected 'else' \u6216 'endifequal'
2017-11-19 15:19:38,292 [Thread-316:12920] [django.request:256] [ERROR]- Internal Server Error: /auth/list/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\myauth\views.py", line 38, in userList
    return render(request, 'list.html', {"form": allUser})
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 868, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 912, in ifequal
    return do_ifequal(parser, token, False)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 883, in do_ifequal
    nodelist_true = parser.parse(('else', end_tag))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'elifequal', expected 'else' \u6216 'endifequal'
2017-11-19 15:19:38,862 [Thread-317:3372] [django.request:256] [ERROR]- Internal Server Error: /auth/list/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\myauth\views.py", line 38, in userList
    return render(request, 'list.html', {"form": allUser})
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 868, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 912, in ifequal
    return do_ifequal(parser, token, False)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 883, in do_ifequal
    nodelist_true = parser.parse(('else', end_tag))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'elifequal', expected 'else' \u6216 'endifequal'
2017-11-19 15:19:38,944 [Thread-318:13012] [django.request:170] [WARNING]- Not Found: /favicon.ico
2017-11-19 15:19:39,848 [Thread-319:14668] [django.request:256] [ERROR]- Internal Server Error: /auth/list/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\myauth\views.py", line 38, in userList
    return render(request, 'list.html', {"form": allUser})
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 868, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 912, in ifequal
    return do_ifequal(parser, token, False)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 883, in do_ifequal
    nodelist_true = parser.parse(('else', end_tag))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'elifequal', expected 'else' \u6216 'endifequal'
2017-11-19 15:19:40,319 [Thread-320:8436] [django.request:256] [ERROR]- Internal Server Error: /auth/list/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\myauth\views.py", line 38, in userList
    return render(request, 'list.html', {"form": allUser})
  File "D:\virtualenv\py27django\lib\site-packages\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 868, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 912, in ifequal
    return do_ifequal(parser, token, False)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\defaulttags.py", line 883, in do_ifequal
    nodelist_true = parser.parse(('else', end_tag))
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\virtualenv\py27django\lib\site-packages\django\template\base.py", line 394, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'elifequal', expected 'else' \u6216 'endifequal'
2017-11-19 15:19:40,398 [Thread-321:9052] [django.request:170] [WARNING]- Not Found: /favicon.ico
2017-11-19 15:22:13,658 [Thread-381:20036] [django.request:170] [WARNING]- Not Found: /favicon.ico
2017-11-23 20:13:16,096 [Thread-19:18032] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 20:13:16,395 [Thread-24:13356] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 20:13:35,211 [Thread-84:16864] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 20:26:36,694 [Thread-106:14628] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 20:26:36,836 [Thread-107:9960] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 20:33:53,467 [Thread-15:7420] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 20:33:53,555 [Thread-16:12908] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 20:34:02,565 [Thread-22:8352] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 20:34:02,651 [Thread-23:15696] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 20:34:50,038 [Thread-29:10816] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 20:34:50,191 [Thread-30:17836] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 20:35:47,470 [Thread-36:7256] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 20:35:47,653 [Thread-37:12304] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 20:35:55,053 [Thread-41:16256] [django.request:170] [WARNING]- Not Found: /bbs/bbsdetail/1/
2017-11-23 20:35:55,433 [Thread-42:14556] [django.request:170] [WARNING]- Not Found: /bbs/bbsdetail/1/
2017-11-23 20:35:55,538 [Thread-43:400] [django.request:170] [WARNING]- Not Found: /favicon.ico
2017-11-23 20:37:09,441 [Thread-103:17568] [django.request:170] [WARNING]- Not Found: /bbs/bbsdetail/1
2017-11-23 20:37:09,690 [Thread-104:16528] [django.request:170] [WARNING]- Not Found: /favicon.ico
2017-11-23 20:38:55,753 [Thread-3:7932] [django.request:170] [WARNING]- Not Found: /bbs/bbsdetail/1
2017-11-23 20:40:19,686 [Thread-43:17284] [django.request:170] [WARNING]- Not Found: /bbs/bbsdetail/1
2017-11-23 20:40:26,260 [Thread-44:7036] [django.request:170] [WARNING]- Not Found: /bbs/1/detail
2017-11-23 20:40:32,290 [Thread-45:12668] [django.request:170] [WARNING]- Not Found: /bbs/detail
2017-11-23 20:40:36,595 [Thread-46:20196] [django.request:170] [WARNING]- Not Found: /bbs/detail/1
2017-11-23 20:41:00,644 [Thread-51:9120] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 20:41:04,657 [Thread-53:6592] [django.request:170] [WARNING]- Not Found: /bbs/bbsdetail/1
2017-11-23 20:43:06,513 [Thread-58:5984] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 20:46:12,766 [Thread-3:6076] [django.request:170] [WARNING]- Not Found: /bbs/1/detail
2017-11-23 20:58:06,230 [Thread-41:18916] [django.request:170] [WARNING]- Not Found: /bbs/edit/
2017-11-23 20:58:06,479 [Thread-42:20008] [django.request:170] [WARNING]- Not Found: /bbs/edit/
2017-11-23 21:17:08,628 [Thread-7:18780] [django.request:256] [ERROR]- Internal Server Error: /bbs/1/update/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\bbs\views.py", line 130, in update
    content = content,
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 422, in update_or_create
    obj, created = self._create_object_from_params(lookup, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 447, in _create_object_from_params
    six.reraise(*exc_info)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 439, in _create_object_from_params
    obj = self.create(**params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\sql\compiler.py", line 963, in execute_sql
    cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\sqlite3\base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: UNIQUE constraint failed: bbs_bbs.id
2017-11-23 21:17:09,088 [Thread-8:400] [django.request:256] [ERROR]- Internal Server Error: /bbs/1/update/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\bbs\views.py", line 123, in update
    user = User.objects.get(username=author)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: User matching query does not exist.
2017-11-23 21:17:09,174 [Thread-9:7944] [django.request:170] [WARNING]- Not Found: /favicon.ico
2017-11-23 21:19:27,944 [Thread-8:6612] [django.request:256] [ERROR]- Internal Server Error: /bbs/1/update/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\bbs\views.py", line 133, in update
    content = content,
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 422, in update_or_create
    obj, created = self._create_object_from_params(lookup, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 447, in _create_object_from_params
    six.reraise(*exc_info)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 439, in _create_object_from_params
    obj = self.create(**params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\sql\compiler.py", line 963, in execute_sql
    cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\backends\sqlite3\base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
IntegrityError: UNIQUE constraint failed: bbs_bbs.id
2017-11-23 21:19:28,385 [Thread-9:16396] [django.request:256] [ERROR]- Internal Server Error: /bbs/1/update/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\bbs\views.py", line 123, in update
    user = User.objects.get(username=author)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: User matching query does not exist.
2017-11-23 21:23:23,375 [Thread-8:588] [django.request:256] [ERROR]- Internal Server Error: /bbs/1/update/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\bbs\views.py", line 123, in update
    user = User.objects.get(username=author)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: User matching query does not exist.
2017-11-23 21:23:32,357 [Thread-10:4876] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 21:24:39,161 [Thread-30:2040] [django.request:256] [ERROR]- Internal Server Error: /bbs/1/update/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "D:\Project\eoms\bbs\views.py", line 123, in update
    user = User.objects.get(username=author)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\db\models\query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: User matching query does not exist.
2017-11-23 21:27:39,585 [Thread-3:14720] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 21:27:39,742 [Thread-4:4968] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 21:27:43,213 [Thread-9:2460] [django.request:256] [ERROR]- Internal Server Error: /bbs/1/details/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
TypeError: bbs_detail() got an unexpected keyword argument 'template_name'
2017-11-23 21:27:43,510 [Thread-10:400] [django.request:256] [ERROR]- Internal Server Error: /bbs/1/details/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
TypeError: bbs_detail() got an unexpected keyword argument 'template_name'
2017-11-23 21:28:51,881 [Thread-2:12156] [django.request:256] [ERROR]- Internal Server Error: /bbs/1/details/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
TypeError: bbs_detail() got an unexpected keyword argument 'template_name'
2017-11-23 21:28:52,292 [Thread-3:4900] [django.request:256] [ERROR]- Internal Server Error: /bbs/1/details/
Traceback (most recent call last):
  File "D:\virtualenv\py27django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\py27django\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
TypeError: bbs_detail() got an unexpected keyword argument 'template_name'
2017-11-23 21:48:20,049 [Thread-58:11776] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
2017-11-23 21:48:20,177 [Thread-59:8024] [django.request:170] [WARNING]- Not Found: /Jumbotron Template for Bootstrap_files/jumbotron.css
